services:
  prode-db:
    container_name: prode-db
    image: mysql:8.0.28
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - prode-data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
  app:
    container_name: prode-app
    depends_on:
      - prode-db
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      JDBC_URL: $APP_JDBC_URL
      DB_USERNAME: $APP_DB_USERNAME
      DB_PASSWORD: $APP_DB_PASSWORD
      JDBC_DRIVER: $APP_JDBC_DRIVER
      HIBERNATE_DIALECT: $APP_HIBERNATE_DIALECT
      JWT_SECRET: $APP_JWT_SECRET
      JWT_EXPIRATION: $APP_JWT_EXPIRATION
      JWT_ISSUER: $APP_JWT_ISSUER
volumes:
  prode-data: