server:
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${JDBC_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
  mvc:
    throw-exception-if-no-handler-found: true
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  issuer: ${JWT_ISSUER}
management:
  endpoints:
    web:
      exposure:
        include: "*"
aws:
  region: ${AWS_REGION}
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
